# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # Prevent log file from being generated by the Ubuntu VM
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end

  # Enable NFS sync
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  # Install necessary packages and dependencies
  config.vm.network "private_network", ip: "192.168.33.99"
    config.vm.provision "shell", inline: <<-SHELL
        sh /vagrant/scripts/apt.sh
        sh /vagrant/scripts/dpkg.sh
        sh /vagrant/scripts/php.sh
        sh /vagrant/scripts/apache.sh
        sh /vagrant/scripts/vim.sh
        sh /vagrant/scripts/composer.sh
        sh /vagrant/scripts/aliases.sh
    SHELL
  end
