version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      - restore_cache:
          keys:
            - princexml-prince_11.3-1_debian8.0_amd64.deb
            - princexml-
      - run:
          name: Download PrinceXML
          command: mkdir -p princexml && wget -nc -O princexml/prince.deb http://www.princexml.com/download/prince_11.3-1_debian8.0_amd64.deb
      - save_cache:
          key: princexml-prince_11.3-1_debian8.0_amd64.deb
          paths:
            - princexml

      - run:
          name: Install PrinceXML
          command: sudo dpkg -i princexml/prince.deb

      - run:
          name: Update Composer to Latest Version
          command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: Test 1 - Code Sniffer
          command: composer gscs

      - run:
          name: Test 2 - PHPUnit
          command: php vendor/bin/phpunit
