version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.0-node-browsers
    working_directory: ~/laravel
    steps:
      - checkout

      - run:
          name: Insatll Python Software Properties
          command: sudo apt-get install -y software-properties-common python-software-properties

      - run:
          name: Add Main Repo
          command: sudo add-apt-repository main

      - run:
          name: Update APT Cache
          command: sudo apt-get update

      - run:
          name: Upgrade libfontconfig1
          command: sudo apt-get install -y --only-upgrade libfontconfig1

      - run:
          name: Install Image Libraries
          command: sudo apt-get install -y libgif7 libjpeg8

      - run:
          name: Install PrinceXML
          command: sudo bash scripts/dpkg.sh

      - run:
          name: Update Composer to Latest Version
          command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist --ignore-platform-reqs
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor

      - run:
          name: Test 1 - Code Sniffer
          command: composer gscs

      - run:
          name: Test 2 - PHPUnit
          command: php vendor/bin/phpunit
